const fishImages: Record<string, string> = {
  "щука": "/fish/pike.png",
  "окунь": "/fish/perch.png",
  "судак": "/fish/zander.png",
  "берш": "/fish/zander.png",
  "сом": "/fish/catfish.png",
  "налим": "/fish/burbot.png",
  "жерех": "/fish/asp.png",
  "голавль": "/fish/chub.png",
  "ротан": "/fish/perch.png",
  "форель": "/fish/trout.png",
  "форель ручьевая": "/fish/trout.png",
  "форель радужная": "/fish/trout.png",
  "таймень": "/fish/trout.png",
  "ленок": "/fish/trout.png",
  "хариус": "/fish/grayling.png",
  "угорь": "/fish/burbot.png",
  "карп": "/fish/carp.png",
  "сазан": "/fish/carp.png",
  "карась": "/fish/crucian.png",
  "карась золотой": "/fish/crucian.png",
  "карась серебряный": "/fish/crucian.png",
  "лещ": "/fish/bream.png",
  "подлещик": "/fish/bream.png",
  "плотва": "/fish/roach.png",
  "вобла": "/fish/roach.png",
  "тарань": "/fish/roach.png",
  "краснопёрка": "/fish/rudd.png",
  "красноперка": "/fish/rudd.png",
  "линь": "/fish/tench.png",
  "амур белый": "/fish/amur.png",
  "амур чёрный": "/fish/amur.png",
  "амур черный": "/fish/amur.png",
  "толстолобик": "/fish/silver-carp.png",
  "толстолобик белый": "/fish/silver-carp.png",
  "толстолобик пёстрый": "/fish/silver-carp.png",
  "толстолобик пестрый": "/fish/silver-carp.png",
  "язь": "/fish/ide.png",
  "елец": "/fish/dace.png",
  "подуст": "/fish/nase.png",
  "усач": "/fish/barbel.png",
  "рыбец": "/fish/nase.png",
  "чехонь": "/fish/asp.png",
  "синец": "/fish/bream.png",
  "белоглазка": "/fish/roach.png",
  "густера": "/fish/bream.png",
  "уклейка": "/fish/bleak.png",
  "верховка": "/fish/bleak.png",
  "пескарь": "/fish/gudgeon.png",
  "ёрш": "/fish/ruffe.png",
  "ерш": "/fish/ruffe.png",
  "вьюн": "/fish/burbot.png",
  "голец": "/fish/trout.png",
  "колюшка": "/fish/gudgeon.png",
  "горчак": "/fish/bleak.png",
  "щиповка": "/fish/gudgeon.png",
  "кутум": "/fish/roach.png",
  "шемая": "/fish/bleak.png",
  "каспийская сельдь": "/fish/bleak.png",
  "каспийская килька": "/fish/bleak.png",
  "тюлька": "/fish/bleak.png",
  "каспийский бычок": "/fish/gudgeon.png",
  "бычок-песочник": "/fish/gudgeon.png",
  "бычок-кругляк": "/fish/gudgeon.png",
  "стерлядь": "/fish/default.png",
  "осётр": "/fish/default.png",
  "осетр": "/fish/default.png",
  "осётр русский": "/fish/default.png",
  "осетр русский": "/fish/default.png",
  "севрюга": "/fish/default.png",
  "белуга": "/fish/default.png",
  "шип": "/fish/default.png",
  "сиг": "/fish/trout.png",
  "ряпушка": "/fish/bleak.png",
  "корюшка": "/fish/bleak.png",
  "омуль": "/fish/trout.png",
  "муксун": "/fish/trout.png",
  "пелядь": "/fish/trout.png",
  "лосось": "/fish/trout.png",
  "лосось атлантический": "/fish/trout.png",
  "горбуша": "/fish/trout.png",
  "кета": "/fish/trout.png",
  "нерка": "/fish/trout.png",
  "кижуч": "/fish/trout.png",
  "кумжа": "/fish/trout.png",
  "треска": "/fish/default.png",
  "пикша": "/fish/default.png",
  "минтай": "/fish/default.png",
  "сайда": "/fish/default.png",
  "хек": "/fish/default.png",
  "камбала": "/fish/default.png",
  "палтус": "/fish/default.png",
  "скумбрия": "/fish/default.png",
  "сельдь": "/fish/bleak.png",
  "сардина": "/fish/bleak.png",
  "ставрида": "/fish/default.png",
  "кефаль": "/fish/default.png",
  "сибас": "/fish/default.png",
  "дорадо": "/fish/default.png",
  "морской окунь": "/fish/perch.png",
  "тунец": "/fish/default.png",
  "луфарь": "/fish/default.png",
  "сарган": "/fish/default.png",
  "барабуля": "/fish/default.png",
};

function normalizeName(name?: string | null) {
  return (name ?? "").trim().toLowerCase();
}

export function FishImage({
  name,
  imageUrl,
  className = "",
}: {
  name?: string | null;
  imageUrl?: string | null;
  className?: string;
}) {
  const normalized = normalizeName(name);
  const src = imageUrl || fishImages[normalized] || "/fish/default.png";

  return (
    <div className={`fish-image ${className}`.trim()}>
      <img src={src} alt={name ?? "Рыба"} loading="lazy" />
    </div>
  );
}
